---
- name: Create a directory /home/vagrant/jenkinsdocker if it does not exist
  ansible.builtin.file:
    path: "/home/vagrant/jenkinsdocker"
    state: directory
    mode: '0755'

# - name: Create a directory jenkins-home if it does not exist
#   ansible.builtin.file:
#     path: "/home/vagrant/jenkinsdocker/jenkins-home"
#     state: directory
#     mode: '0755'

- name: copy files
  copy:
    src: files/{{ item }}
    dest: /home/vagrant/jenkinsdocker/{{ item }}
  loop:
      - docker-compose.yml
      - Dockerfile
      - plugins.txt

# - name: Copy sonar-scanner
#   ansible.builtin.copy:
#     src: files/sonar-scanner-4.6.2.2472/
#     dest: /home/vagrant/jenkinsdocker/sonar-scanner/

- name: copy Template jenkins-casc.yaml
  template:
    src: jenkins-casc.yaml.j2
    dest: /home/vagrant/jenkinsdocker/jenkins-casc.yaml

- name: copy Template seedjob_multipipeline.groovy
  template:
    src: seedjob_multipipeline.groovy.j2
    dest: /home/vagrant/jenkinsdocker/seedjob_multipipeline.groovy
...