---
- name: Container is stopped
  community.docker.docker_container:
    name: "{{ jenkins_docker_container_name }}"
    image: "{{ jenkins_docker_image }}:{{ jenkins_version }}"
    published_ports: "{{ jenkins_port }}:8080"
    container_default_behavior: "no_defaults"
    volumes:
      - "{{ jenkins_home }}:/var/jenkins_home"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"
    state: stopped

- name: Wait for container to stop
  wait_for:
    timeout: 5
