# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
   config.env.enable

  config.vm.box = "ubuntu/focal64"

  config.vm.define ENV['JENKINSMAIN_NAME'] do |t|
  end

  
   config.vm.hostname = ENV['JENKINSMAIN_NAME']

  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV['JENKINSMAIN_NAME']
    vb.gui = false
    vb.memory = ENV['JENKINSMAIN_MEMORY']
  end

  config.vm.network "public_network", bridge: ENV['HOST_BRIDGE'], ip: ENV['JENKINSMAIN_IP'], hostname: true

end