---
- name: Install Nginx Web Server
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd

- meta: flush_handlers

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf

- name: Replace nginx.conf
  template:
    src=templates/index.html.j2
    dest=/var/www/html/index.html
  notify:
    - nginx restart

- meta: flush_handlers
...