---
version: "3.9"
services:
  jenkins:
    container_name: jenkins-casc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins-home:/var/jenkins_home
volumes:
  jenkins-home:
...