---

- name: Playbook for add user jenkins for jenkinsmain
  gather_facts: true
  hosts: jenkinsmain
  remote_user: vagrant
  become: true

  tasks:
  
    - name: Add the user 'jenkins'
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash


- name: Playbook for add user jenkinsnode for jenkinsnode
  gather_facts: true
  hosts: jenkinsnode
  remote_user: vagrant
  become: true

  tasks:
    - name: Add the user 'jenkinsnode'
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', './.keys/jenkinsmain/id_rsa_jenkinsmain.pub') }}"

- name: Playbook for add user jenkinsnode for jenkinsnode
  gather_facts: true
  hosts: deploy
  remote_user: vagrant
  become: true

  tasks:
    - name: Add the user 'jenkinsnode'
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash
        group: sudo

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', './.keys/jenkinsmain/id_rsa_jenkinsmain.pub') }}"

    - name: Ensuring that wheel is able to use sudo without password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


    - name: Add user to sudoers file
      lineinfile:
        path: /etc/sudoers
        regexp: '^jenkins'
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add user "ansibleuser" to sudo
      lineinfile:
        path: /etc/sudoers.d/jenkins
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'

    - name: Set includedir in sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"
...