---
all:
  hosts:
    jenkinsmain:
    jenkinsnode1:
    sonarqube:
    prod:
    dev:
    nexus:
  children:
    vagrants:
      hosts:
        jenkinsmain:
        jenkinsnode1:
        sonarqube:
        prod:
        dev:
        nexus:
    docker:
      hosts:
        jenkinsmain:
        sonarqube:
        prod:
        dev:
    node:
      hosts:
        jenkinsmain:
        jenkinsnode1:
    jenkins:
      hosts:
        jenkinsmain:
    jenkinsnode:
      hosts:
        jenkinsnode1:
    java:
      hosts:
        jenkinsnode1:
        nexus:
...