---

- name: Playbook for ngrok installation
  gather_facts: true
  hosts: jenkins
  become: true
  remote_user: vagrant

  vars_files:
      - ../.keys/ngrok/secrets.yml

  vars:

    #ngrok_auth_token: qwerty12345
    ngrok_console_ui: "true"
    ngrok_install_as_service: false
    ngrok_tunnels:
      - name:       "jenkinsmain"
        #hostname:   "my-custom-host.ngrok.io"    # optional
        #subdomain:  "my-custom-subdomain"        # subdomain for ngrok.io (optional), only used if hostname is not defined.
                                                # if subdomain is also not defined, ngrok uses tunnel name as subdomain
        address:    "localhost:8080"
        proto:      "http"                       # optional, default: http
        bind_tls:   false #both                         # optional, default: both (false: only http, true: only https, both: http & https)
        # auth:
        #   username: "anmorgul"
        #   password: "NgPa541fyv"

  roles:
    - votum.ngrok
...