---

- name: Playbook for node.js and npm installation
  gather_facts: true
  hosts: jenkinsnode
  remote_user: vagrant
  become: true
  serial: 5
  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: true
  - name: Upgrade all apt packages
    apt: upgrade=yes force_apt_get=yes
    become: true

  - name: Install Python pip
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items:
    - python3-pip
    - unzip
    become: true

  - name: Install Python packages
    pip: name={{ item }}
    with_items:
    - ansible
    become: true
...