---

- name: Playbook for jenkins installation
  gather_facts: true
  hosts: jenkins
  become: true
  remote_user: vagrant

  vars_files:
      - ../.keys/jenkinsmain/secrets.yml
  vars:
    jenkins_health_check_user: "admin"
    jenkins_health_check_password: "Qwerty12345"
    jenkins_version: "jenkins"
    #jenkins_version: "lts-jdk11"
    jenkins_hostname: "jenkinsmain"
    jenkins_port: 8080


  roles:
    - jenkins