---

- name: Playbook for sonarcube installation
  gather_facts: true
  hosts: sonarqube
  become: true
  remote_user: vagrant

  vars_files:
      - ./.keys/sonarqube/secrets.yml
      - ./.keys/sonarqube/project_name.yml

  # vars:

  roles:
    - sonarcube
...