---

- name: Playbook for java installation
  gather_facts: true
  hosts: java
  remote_user: vagrant
  serial: 5

  tasks:
    - name: Install java
      become: true
      ansible.builtin.apt:
        name:
          - openjdk-11-jdk
        state: present
        update_cache: yes
...