---

- name: Playbook for jenkins installation
  gather_facts: true
  hosts: jenkins
  become: true
  remote_user: vagrant

  vars_files:
      - ./.keys/jenkinsmain/secrets.yml
      - ./.keys/sonarqube/.sonarqube_token.yml
      - ./.keys/sonarqube/project_name.yml
      - ./.keys/jenkinsmain/telegram.yml
      - ./.keys/nexus/jenkins_pass.yml
  vars:
    jenkins_version: "jenkins"
    #jenkins_version: "lts-jdk11"
    jenkins_hostname: "jenkinsmain"
    jenkins_port: 8080


  roles:
    - jenkins
...