---

- name: Playbook for remove snapd
  gather_facts: true
  hosts: vagrants
  serial: 7
  remote_user: vagrant
  become: true

  tasks:
    - name: Remove snapd from Ubuntu
      apt:
        name: snapd
        state: absent
        purge: yes

    - name: Remove snapd-related directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /snap
        - /var/snap
        - /var/lib/snapd
        # - /home/bwenrich/snap
